const category = [
  { title: "MenFootwear", path: "/images/footwear.jpg" },
  { title: "MenTopwear", path: "/images/men_topwear.jpg" },
  { title: "WomenTopwear", path: "/images/women_topwear.jpg" },
  { title: "WomenFootwear", path: "/images/footwear_women.jpg" },
  { title: "Watch", path: "/images/watches.jpg" },
  { title: "Headphone", path: "/images/headphone.jpg" },
  { title: "Mobile", path: "/images/mobile.png" },
  { title: "Laptop", path: "/images/laptop.png" },
];

export default function getCategory() {
  const categoryList = [...category];
  return categoryList;
}

const item = [
  {
    path: "https://m.media-amazon.com/images/I/71UktxaQtNL._AC_UL320_.jpg",
    title: "Men's Sandals & Floaters",
    rating: "3.9 out of 5 stars",
    dis_price: "729",
    org_price: "?2,299",
    discount: "Save ?1,570 (68%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/51NFCh2FXIL._AC_UL320_.jpg",
    title:
      "Mens Footwear |Kolhapuri Pure Leather Handmade Chappal| Ethnic Slippers for Mens KOLAHPURI_2",
    rating: "",
    dis_price: "1,400",
    org_price: "?2,799",
    discount: "Save ?1,399 (50%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61KlBPw9ZsL._AC_UL320_.jpg",
    title:
      "Extra Soft Doctor Ortho Care Orthopedic Diabetic MCR Dr Comfortable Light Weight Daily Use brandvilla Flip Flops Footwear Slippers for Men Gents Boys",
    rating: "3.8 out of 5 stars",
    dis_price: "367",
    org_price: "?699",
    discount: "Save ?332 (47%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/611Z9wouxhL._AC_UL320_.jpg",
    title:
      "Karam ISI Marked Men's Executive Sporty Lace Up Safety Footwear (Brown, fs61br, 9)",
    rating: "4.5 out of 5 stars",
    dis_price: "3,550",
    org_price: "?3,999",
    discount: "Save ?449 (11%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81NjOfeAt2L._AC_UL320_.jpg",
    title: "Slippers & Flip Flops for Men",
    rating: "3.1 out of 5 stars",
    dis_price: "299",
    org_price: "?900",
    discount: "Save ?601 (67%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71PXlz+rp+L._AC_UL320_.jpg",
    title: "SLICKERS Men's Blue Sandals",
    rating: "4.1 out of 5 stars",
    dis_price: "299",
    org_price: "",
    discount: "FREE Delivery on your first order in this category",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71qZGLrsU2L._AC_UL320_.jpg",
    title: "Men's Krypton Action Brown Hawaii Thong Sandals",
    rating: "4.1 out of 5 stars",
    dis_price: "399",
    org_price: "?499",
    discount: "Save ?100 (20%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71PAi7YraiL._AC_UL320_.jpg",
    title: "Men's Mustard Slippers-10 UK/India (44 EU) (A1PU6758GMSD00010G319)",
    rating: "4.1 out of 5 stars",
    dis_price: "314",
    org_price: "?319",
    discount: "Save ?5 (2%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71PAi7YraiL._AC_UL320_.jpg",
    title: "Men's Mustard Slippers-9 UK/India (43 EU) (A1PU6758GMSD00009G319)",
    rating: "4.1 out of 5 stars",
    dis_price: "314",
    org_price: "?319",
    discount: "Save ?5 (2%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71PAi7YraiL._AC_UL320_.jpg",
    title: "Men's Vertex Mustard Footwear-8 UK (Invalid Data)",
    rating: "4.1 out of 5 stars",
    dis_price: "309",
    org_price: "",
    discount: "FREE Delivery on your first order in this category",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81acjfWdO2L._AC_UL320_.jpg",
    title: "Men's Sf0541g Flip Flop",
    rating: "3.9 out of 5 stars",
    dis_price: "317",
    org_price: "?374",
    discount: "Save ?57 (15%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71v553n3d2L._AC_UL320_.jpg",
    title: "Men's Miracle Sandals Slippers",
    rating: "3.3 out of 5 stars",
    dis_price: "799",
    org_price: "?999",
    discount: "Save ?200 (20%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71SvSwcrmZL._AC_UL320_.jpg",
    title: "Men's Flip-Flop",
    rating: "4.3 out of 5 stars",
    dis_price: "309",
    org_price: "",
    discount: "FREE Delivery on your first order in this category",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71PAi7YraiL._AC_UL320_.jpg",
    title: "Men's Vertex Mustard Footwear-6 UK (A1PU6758GMSD00006G319)",
    rating: "4.0 out of 5 stars",
    dis_price: "319",
    org_price: "",
    discount: "FREE Delivery on your first order in this category",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/815zUgZEhLL._AC_UL320_.jpg",
    title: "Men's F.Lite Leather Hawaii Thong Sandals",
    rating: "4.3 out of 5 stars",
    dis_price: "423",
    org_price: "?499",
    discount: "Save ?76 (15%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71YAbRMjkfL._AC_UL320_.jpg",
    title: "Men's Jubilee Leather Slipper",
    rating: "4.2 out of 5 stars",
    dis_price: "314",
    org_price: "?449",
    discount: "Save ?135 (30%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/51C5Scd8o1L._AC_UL320_.jpg",
    title: "Mens Black Slipper -10",
    rating: "4.0 out of 5 stars",
    dis_price: "370",
    org_price: "?699",
    discount: "Save ?329 (47%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71lZEgZ+UCL._AC_UL320_.jpg",
    title: "Men's Krypton Soft Slipper",
    rating: "4.1 out of 5 stars",
    dis_price: "479",
    org_price: "?599",
    discount: "Save ?120 (20%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/91HXxeY0JpL._AC_UL320_.jpg",
    title: "Men Grey-Black Slipper-8 UK (FIT003G)",
    rating: "4.3 out of 5 stars",
    dis_price: "122",
    org_price: "?129.50",
    discount: "Save ?7.50 (6%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71Q88XJu7zL._AC_UL320_.jpg",
    title:
      "Slipper Ortho Care Orthopaedic and Diabetic Super Fit Comfort Doctor Slipper, Dr. Slipper, Flip-Flop, Slides and House Slipper for Men's D-24",
    rating: "4.1 out of 5 stars",
    dis_price: "469",
    org_price: "?999",
    discount: "Save ?530 (53%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71LTso3y4XL._AC_UL320_.jpg",
    title: "Men's Sandals & Floaters",
    rating: "3.8 out of 5 stars",
    dis_price: "769",
    org_price: "?2,299",
    discount: "Save ?1,530 (67%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/41+qtBLBKaL._AC_UL320_.jpg",
    title: "HealthFit Men's PU Diabetic & Orthopedic Slipper",
    rating: "3.9 out of 5 stars",
    dis_price: "634",
    org_price: "?699",
    discount: "Save ?65 (9%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71YnPFOkoQL._AC_UL320_.jpg",
    title: "Men's 2029 Sandals",
    rating: "3.4 out of 5 stars",
    dis_price: "499",
    org_price: "?999",
    discount: "Save ?500 (50%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71Zpcq1VeHS._AC_UL320_.jpg",
    title: "Men's 3655 Sandals",
    rating: "4.0 out of 5 stars",
    dis_price: "709",
    org_price: "?2,299",
    discount: "Save ?1,590 (69%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81P8t+CLA2L._AC_UL320_.jpg",
    title: "Men's Denim Flip-Flops and House Slippers",
    rating: "4.2 out of 5 stars",
    dis_price: "296",
    org_price: "?329",
    discount: "Save ?33 (10%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71-mzj6ZX1L._AC_UL320_.jpg",
    title: "Men Flip-Flop",
    rating: "4.2 out of 5 stars",
    dis_price: "139",
    org_price: "",
    discount: "FREE Delivery on your first order in this category",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81AmVWKOrKL._AC_UL320_.jpg",
    title: "Slippers & Flip Flops for Men",
    rating: "3.5 out of 5 stars",
    dis_price: "299",
    org_price: "?900",
    discount: "Save ?601 (67%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81y7X+u5PGL._AC_UL320_.jpg",
    title:
      "Men's Faux Leather Slipper - Flat Chappal cum Thong Sandal - For Daily Use Outdoor Indoor Formal Office Home Ethnic Casual Wear",
    rating: "4.0 out of 5 stars",
    dis_price: "299",
    org_price: "?999",
    discount: "Save ?700 (70%)",
    category: "MenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71yawnKDgjL._AC_UL320_.jpg",
    title:
      "PARAGON Men's Brown Formal Thong Sandals-9 UK/India (43 EU)(PU6728-62)",
    rating: "4.2 out of 5 stars",
    dis_price: "299",
    org_price: "",
    discount: "FREE Delivery on your first order in this category",
    category: "MenFootwear",
  },

  {
    path: "https://m.media-amazon.com/images/I/71FnRZF3D5L._AC_UL320_.jpg",
    title: "Marks and Spencer Women's bottomwear Regular Pants",
    rating: "5.0 out of 5 stars",
    dis_price: "1,719",
    org_price: "?2,499",
    discount: "Save ?780 (31%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71Hbs4eRHcL._AC_UL320_.jpg",
    title: "Marks and Spencer Women's Bottomwear Loose Pants",
    rating: "3.6 out of 5 stars",
    dis_price: "749",
    org_price: "?2,999",
    discount: "Save ?2,250 (75%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71-qLHSaCvL._AC_UL320_.jpg",
    title: "Marks and Spencer Women's Bottomwear Regular Pants",
    rating: "5.0 out of 5 stars",
    dis_price: "999",
    org_price: "?3,999",
    discount: "Save ?3,000 (75%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71-DkN8VP2L._AC_UL320_.jpg",
    title: "Marks and Spencer Women's bottomwear Leggings",
    rating: "5.0 out of 5 stars",
    dis_price: "999",
    org_price: "",
    discount: "FREE Delivery by Amazon",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/715R0xJ508L._AC_UL320_.jpg",
    title: "Marks and Spencer Women's Bottomwear Slim Pants",
    rating: "4.2 out of 5 stars",
    dis_price: "803",
    org_price: "?1,999",
    discount: "Save ?1,196 (60%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61TddtaPfKL._AC_UL320_.jpg",
    title: "Marks and Spencer Women's bottomwear Leggings",
    rating: "4.2 out of 5 stars",
    dis_price: "789",
    org_price: "?999",
    discount: "Save ?210 (21%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81XDCRsbhhL._AC_UL320_.jpg",
    title: "Marks and Spencer Women's Bottomwear Loose Pants",
    rating: "3.0 out of 5 stars",
    dis_price: "1,797",
    org_price: "?4,499",
    discount: "Save ?2,702 (60%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71OgPRXA2mL._AC_UL320_.jpg",
    title: "Marks and Spencer Women's Bottomwear Regular Track Pants",
    rating: "4.3 out of 5 stars",
    dis_price: "1,298",
    org_price: "?1,299",
    discount: "Save ?1",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/51EDsqBsjJL._AC_UL320_.jpg",
    title: "Womens Winter Brown Acrylic Warm Bottomwear with Slit",
    rating: "",
    dis_price: "999",
    org_price: "?1,449",
    discount: "Save ?450 (31%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61C4EX1I50L._AC_UL320_.jpg",
    title:
      "Women's Cotton Plain Capri, Capri Pants Loose Yoga Pants,Plain Capri for Women, Nightwear Capri for Women",
    rating: "3.5 out of 5 stars",
    dis_price: "599",
    org_price: "?999",
    discount: "Save ?400 (40%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/51RcAjYkCML._AC_UL320_.jpg",
    title:
      "Women Girls Casual Formal Western Stylish Cotton Trouser Regular Fit Plain Pyajama Pants Lowers Bottomwear Officewear Joggers Jeggings",
    rating: "3.3 out of 5 stars",
    dis_price: "329",
    org_price: "?999",
    discount: "Save ?670 (67%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61u+Wuk9XXL._AC_UL320_.jpg",
    title:
      "Women Girls Casual Formal Western Stylish Cotton Trouser Regular Fit Plain Pyajama Pants Lowers Bottomwear Officewear Joggers Jeggings (Color-Green)",
    rating: "3.0 out of 5 stars",
    dis_price: "329",
    org_price: "?1,299",
    discount: "Save ?970 (75%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71j2IuZS0GL._AC_UL320_.jpg",
    title: "Womens Cotton Printed Capri & Top Set,Nightsuit",
    rating: "4.0 out of 5 stars",
    dis_price: "618",
    org_price: "",
    discount: "FREE Delivery by Amazon",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/41U39kaFJES._AC_UL320_.jpg",
    title:
      "Women Girls Casual Formal Western Stylish Cotton Trouser Regular Fit Plain Pyajama Pants Lowers Bottomwear Officewear Joggers Jeggings (Color-White)",
    rating: "3.1 out of 5 stars",
    dis_price: "329",
    org_price: "?1,299",
    discount: "Save ?970 (75%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71EmwaHGRuL._AC_UL320_.jpg",
    title:
      "Women's Nightwear Pajamas Lounge Pants Lounge Wear Pyjamas for Women Pajamas Bottomwear Payjamas Size XS S M L",
    rating: "4.0 out of 5 stars",
    dis_price: "349",
    org_price: "?699",
    discount: "Save ?350 (50%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81pOlqA5BtL._AC_UL320_.jpg",
    title:
      "Women & Girls Track Pant Lower Pajama Cotton Printed Lounge Wear Soft Cotton Night Wear (Pack of 5) Multicolor (3, X-Large)",
    rating: "2.4 out of 5 stars",
    dis_price: "464",
    org_price: "?999",
    discount: "Save ?535 (54%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/51dzunLH7CL._AC_UL320_.jpg",
    title:
      "Women's Cotton Viscose Lycra Dhoti Patiyala Salwar Harem Bottoms Pants",
    rating: "3.9 out of 5 stars",
    dis_price: "339",
    org_price: "?999",
    discount: "Save ?660 (66%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61QgBptgG9L._AC_UL320_.jpg",
    title: "Women's Palazzo Bottom",
    rating: "4.0 out of 5 stars",
    dis_price: "562",
    org_price: "?1,199",
    discount: "Save ?637 (53%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/7199TfqidyL._AC_UL320_.jpg",
    title: "Women's Palazzo Straight Bottom",
    rating: "4.0 out of 5 stars",
    dis_price: "533",
    org_price: "?1,199",
    discount: "Save ?666 (56%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/91xYRw1CHlL._AC_UL320_.jpg",
    title: "Men Women Summer Sleepwear Harem Pants",
    rating: "4.2 out of 5 stars",
    dis_price: "567",
    org_price: "?1,999",
    discount: "Save ?1,432 (72%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71VBuAI0CxL._AC_UL320_.jpg",
    title:
      "Women's Loose Fit Patiala Pants (Pack of 3)(Kris-patiala-3_Black_40)",
    rating: "3.2 out of 5 stars",
    dis_price: "499",
    org_price: "?999",
    discount: "Save ?500 (50%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71mR6REXzcL._AC_UL320_.jpg",
    title: "Marks and Spencer Women's Bottomwear Slim Pants",
    rating: "4.5 out of 5 stars",
    dis_price: "2,661",
    org_price: "?4,499",
    discount: "Save ?1,838 (41%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/31qvw8EzT2L._AC_UL320_.jpg",
    title:
      "Shrishti Women's/Girls Woollen/Fleece Stretchable Solid Pyjama Regular Fit Nightwear Warm Winter Wear (Waist Size: 28 - 34 Inches, Free Size 28 Till 34, Grey, Light Brown)",
    rating: "2.9 out of 5 stars",
    dis_price: "345",
    org_price: "?899",
    discount: "Save ?554 (62%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71Rd8nYUrrL._AC_UL320_.jpg",
    title: "Marks and Spencer Women's Bottomwear Skinny Track Pants",
    rating: "2.5 out of 5 stars",
    dis_price: "1,519",
    org_price: "?1,999",
    discount: "Save ?480 (24%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61r+ZK+jPtL._AC_UL320_.jpg",
    title: "Women's Slim Fit Casual Trousers",
    rating: "4.1 out of 5 stars",
    dis_price: "388",
    org_price: "?1,699",
    discount: "Save ?1,311 (77%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/91zrHyakVVL._AC_UL320_.jpg",
    title: "Women's Jegging Western Casual Pants",
    rating: "",
    dis_price: "1,367",
    org_price: "?1,799",
    discount: "Save ?432 (24%)",
    field7: "",
    category: "WomenFootwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/7136ibeedOL._AC_UL320_.jpg",
    title: "Marks and Spencer Women's Bottomwear Regular Casual Pants",
    rating: "4.7 out of 5 stars",
    dis_price: "935",
    org_price: "?1,299",
    discount: "Save ?364 (28%)",
    field7: "",
    category: "WomenFootwear",
  },

  {
    path: "https://m.media-amazon.com/images/I/81wh7iz6-nL._AC_UL320_.jpg",
    title: "Printed Bell Sleeve Wrap & Swing Top",
    rating: "3.5 out of 5 stars",
    dis_price: "359",
    org_price: "?1,299",
    discount: "Save ?940 (72%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/717fb7eCyCL._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Quarter Sleevs Round Neck Hand Embroidery Tunic Topwear for Women | Stylish Casual | Office wear | Fancy | - Grey & White",
    rating: "",
    dis_price: "1,499",
    org_price: "?2,299",
    discount: "Save ?800 (35%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71zxOq5486L._AC_UL320_.jpg",
    title:
      "Premium Soft Poly Silk Quarter Sleeves Round Neck Hand Embroidery Tunic Topwear for Women | Stylish Casual | Office wear | Fancy | Maroon & Baby Pink",
    rating: "",
    dis_price: "1,499",
    org_price: "?2,999",
    discount: "Save ?1,500 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/615jVnEgfCS._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Quarter Sleeve Round Neck Hand Embroidery Chickenkari Tunic Topwear for Women | Stylish Casual | Fancy | - White 12 White for Women",
    rating: "",
    dis_price: "999",
    org_price: "?1,999",
    discount: "Save ?1,000 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61pahCdtsGS._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Quarter Sleeve Round Neck Hand Embroidery Chickenkari Tunic Topwear for Women | Stylish Casual | Fancy | - White with Navy 3 White for Women",
    rating: "",
    dis_price: "899",
    org_price: "?1,999",
    discount: "Save ?1,100 (55%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71jO9qc-HlL._AC_UL320_.jpg",
    title:
      "Premium Soft Poly Silk Quarter Sleeves Round Neck Hand Embroidery Tunic Topwear for Women | Stylish Casual | Office wear | Fancy | Maroon",
    rating: "",
    dis_price: "1,499",
    org_price: "?2,999",
    discount: "Save ?1,500 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71PGPgaZTHL._AC_UL320_.jpg",
    title:
      "Premium Soft Poly Silk Quarter Sleeves Round Neck Hand Embroidery Tunic Topwear for Women | Casual | Office wear | | Multicolor",
    rating: "",
    dis_price: "1,499",
    org_price: "?2,999",
    discount: "Save ?1,500 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/616ugeQqhGS._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Quarter Sleeve Round Neck Hand Embroidery Chickenkari Tunic Topwear for Women | Stylish Casual | Fancy | - White 5 White for Women",
    rating: "",
    dis_price: "1,099",
    org_price: "?2,299",
    discount: "Save ?1,200 (52%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71sd0hyWEgL._AC_UL320_.jpg",
    title:
      "Premium Soft Poly Silk Round Neck Hand Embroidery Tunic Topwear for Women | Stylish Casual | Office wear | Fancy | Grey",
    rating: "",
    dis_price: "1,499",
    org_price: "?2,999",
    discount: "Save ?1,500 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71NKoSg3v5L._AC_UL320_.jpg",
    title:
      "Premium Soft Poly Silk Quarter Sleeves Round Neck Hand Embroidery Tunic Topwear for Women | Stylish Casual | Office wear | Fancy | Blue",
    rating: "",
    dis_price: "1,499",
    org_price: "?2,999",
    discount: "Save ?1,500 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71dOhgAD1KL._AC_UL320_.jpg",
    title:
      "Premium Soft Poly Silk Quarter Sleeves Round Neck Hand Embroidery Tunic Topwear for Women | Casual | Office wear | Multicolor | Multicolor",
    rating: "5.0 out of 5 stars",
    dis_price: "1,399",
    org_price: "?2,799",
    discount: "Save ?1,400 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/614FmNMV+rS._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Sleeve Less Round Neck Hand Embroidery Chickenkari Tunic Topwear for Women | Stylish Casual | Fancy | White Small",
    rating: "",
    dis_price: "999",
    org_price: "?1,999",
    discount: "Save ?1,000 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61z6JxAdARL._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Sleeveless Round Neck Hand Embroidery Tunic Topwear for Women | Stylish Casual | Office wear | Fancy | White & Dark Blue",
    rating: "",
    dis_price: "1,299",
    org_price: "?1,899",
    discount: "Save ?600 (32%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/51FVIatwAcL._AC_UL320_.jpg",
    title: "Anwija Tunic top with Jacket in Print",
    rating: "3.8 out of 5 stars",
    dis_price: "549",
    org_price: "?999",
    discount: "Save ?450 (45%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/91iFZa3DH8L._AC_UL320_.jpg",
    title: "Women's Polka Dot Regular Fit Fashion Vest (M-SER-BT-1- White XL)",
    rating: "3.6 out of 5 stars",
    dis_price: "330",
    org_price: "?1,999",
    discount: "Save ?1,669 (83%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81Qelj0EE2L._AC_UL320_.jpg",
    title: "Women's Regular Top",
    rating: "4.1 out of 5 stars",
    dis_price: "379",
    org_price: "?1,499",
    discount: "Save ?1,120 (75%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71a1Y61VUcL._AC_UL320_.jpg",
    title: "Women Top",
    rating: "5.0 out of 5 stars",
    dis_price: "399",
    org_price: "?1,499",
    discount: "Save ?1,100 (73%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61XBbkS5DSL._AC_UL320_.jpg",
    title: "Women's Regular Top",
    rating: "5.0 out of 5 stars",
    dis_price: "379",
    org_price: "?1,499",
    discount: "Save ?1,120 (75%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71jeIc6f18L._AC_UL320_.jpg",
    title: "Women's Regular Top",
    rating: "4.9 out of 5 stars",
    dis_price: "379",
    org_price: "?1,499",
    discount: "Save ?1,120 (75%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71NRUs8BHqL._AC_UL320_.jpg",
    title:
      "Women's Multisport Wear - Fitness Top (Half Sleeves) | V Flex | Upper Printed Patch with Piping [High Neck with YKK Zip]",
    rating: "",
    dis_price: "835",
    org_price: "?879",
    discount: "Save ?44 (5%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/816xb27Sg6L._AC_UL320_.jpg",
    title:
      "Premium Soft Poly Silk Half Sleeve V Neck Kaftan Hand Embroidery Kaftan Topwear for Women | Stylish Casual | Office wear | Fancy | White",
    rating: "5.0 out of 5 stars",
    dis_price: "1,599",
    org_price: "?2,999",
    discount: "Save ?1,400 (47%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71LP7cR9kbL._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Sleeveless Round Neck Hand Embroidery Tunic Topwear for Women | Stylish Casual | Office wear | Fancy | - Pink & White",
    rating: "",
    dis_price: "1,299",
    org_price: "?1,899",
    discount: "Save ?600 (32%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61m+5W31VdS._AC_UL320_.jpg",
    title:
      "Soft Cotton Quater Length Chinese Collar Embroidery Tunic Topwear for Women | Stylish Casual | Fancy | White",
    rating: "5.0 out of 5 stars",
    dis_price: "1,149",
    org_price: "?1,999",
    discount: "Save ?850 (43%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61Xoj9afnsS._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Quarter Sleeve V Neck Hand Embroidery Chickenkari Tunic Topwear for Women | Stylish Casual | Fancy | - White with Navy Blue 1 White for Women",
    rating: "1.0 out of 5 stars",
    dis_price: "999",
    org_price: "?1,999",
    discount: "Save ?1,000 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71Qb-Jo0F1L._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Sleeveless Round Neck Hand Embroidery Tunic Topwear for Women | Stylish Casual | Office wear | Fancy | Dark Blue & White",
    rating: "",
    dis_price: "1,299",
    org_price: "?1,899",
    discount: "Save ?600 (32%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/31YTeDUh2zS._AC_UL320_.jpg",
    title:
      "Premium Soft Polysilk Quarter Sleeves Round Neck Hand Embroidery Tunic Topwear for Women | Stylish Casual | Office wear | Fancy | Blue",
    rating: "",
    dis_price: "1,499",
    org_price: "?2,999",
    discount: "Save ?1,500 (50%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61Q493Vm5qS._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Full Sleeve Round Neck Hand Embroidery Chickenkari Tunic Topwear for Women | Stylish Casual | Fancy | - White 11 White for Women",
    rating: "",
    dis_price: "1,099",
    org_price: "?1,999",
    discount: "Save ?900 (45%)",
    field7: "",
    category: "WomenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61R9wRrV-3S._AC_UL320_.jpg",
    title:
      "Premium Soft Cotton Quarter Sleeve Round Neck Hand Embroidery Chickenkari Tunic Topwear for Women | Stylish Casual | Fancy | - White 19 White for Women",
    rating: "",
    dis_price: "1,599",
    org_price: "?2,499",
    discount: "Save ?900 (36%)",
    field7: "",
    category: "WomenTopwear",
  },

  {
    path: "https://m.media-amazon.com/images/I/71lv87z1MQL._AC_UL320_.jpg",
    title:
      "Green and Black Graphic Printed Printed Tshirts for Men(Pack of 2)-T_4_GRN_5_BLK_02-P",
    rating: "3.1 out of 5 stars",
    dis_price: "549",
    org_price: "?1,998",
    discount: "Save ?1,449 (73%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81PdLboUOnL._AC_UL320_.jpg",
    title: "Men's Slim Fit T-Shirt (Pack of 6)",
    rating: "3.8 out of 5 stars",
    dis_price: "999",
    org_price: "?5,994",
    discount: "Save ?4,995 (83%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/51Pj5TUKcpL._AC_UL320_.jpg",
    title: "Mens Latest Installing Muscles Design Roundneck Halfsleeve Tshirts",
    rating: "4.0 out of 5 stars",
    dis_price: "379",
    org_price: "?799",
    discount: "Save ?419.95 (53%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81sMZaXmOqL._AC_UL320_.jpg",
    title: "Punisher Featured Olive Tshirt for Men",
    rating: "4.6 out of 5 stars",
    dis_price: "310",
    org_price: "?699",
    discount: "Save ?389 (56%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/715yXWCEYBL._AC_UL320_.jpg",
    title: "Men's Thermal Top",
    rating: "3.3 out of 5 stars",
    dis_price: "199",
    org_price: "?399",
    discount: "Save ?200 (50%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61RKR+dMEvL._AC_UL320_.jpg",
    title: "Men VEST",
    rating: "4.1 out of 5 stars",
    dis_price: "267",
    org_price: "?339",
    discount: "Save ?72 (21%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81C52d9K0+L._AC_UL320_.jpg",
    title: "Men's Plain Thermal Top",
    rating: "4.1 out of 5 stars",
    dis_price: "618",
    org_price: "?649",
    discount: "Save ?31 (5%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/91C7hxgbGWL._AC_UL320_.jpg",
    title: "Mens Cotton Thermal Top",
    rating: "4.1 out of 5 stars",
    dis_price: "435",
    org_price: "?500",
    discount: "Save ?65 (13%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81PaKtEAIZL._AC_UL320_.jpg",
    title: "Men's Cotton Vest (Pack of 6)",
    rating: "3.9 out of 5 stars",
    dis_price: "362",
    org_price: "?399",
    discount: "Save ?37 (9%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61o+1H07hGL._AC_UL320_.jpg",
    title:
      "Levi�s Men�s 100% Cotton 100 CA Classic Solid White Vest- Modern Fit (Pack of 3)",
    rating: "4.2 out of 5 stars",
    dis_price: "374",
    org_price: "?499",
    discount: "Save ?125 (25%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71Y+PvZTDxS._AC_UL320_.jpg",
    title: "Jon Men's Cotton Vest (Pack of 5)",
    rating: "4.1 out of 5 stars",
    dis_price: "315",
    org_price: "?450",
    discount: "Save ?135 (30%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/710K01Rzj7L._AC_UL320_.jpg",
    title: "Men's Vest (Pack of 3)",
    rating: "3.9 out of 5 stars",
    dis_price: "799",
    org_price: "?1,499",
    discount: "Save ?700 (47%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71LLOxzKidS._AC_UL320_.jpg",
    title: "Boys Unisex-Baby Men Vest",
    rating: "4.2 out of 5 stars",
    dis_price: "537",
    org_price: "",
    discount: "FREE Delivery by Amazon",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71SMA0PaHbL._AC_UL320_.jpg",
    title: "Men's Cotton Undershirt (Modern Classic)",
    rating: "4.2 out of 5 stars",
    dis_price: "229",
    org_price: "",
    discount: "FREE Delivery on your first order in this category",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81ePid73akL._AC_UL320_.jpg",
    title: "Men's Cotton Thermal Vest",
    rating: "4.2 out of 5 stars",
    dis_price: "669",
    org_price: "",
    discount: "FREE Delivery by Amazon",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/71qTsAYhzKS._AC_UL320_.jpg",
    title: "Men's Cotton Vest (Pack of 3)",
    rating: "4.0 out of 5 stars",
    dis_price: "199",
    org_price: "?299",
    discount: "Save ?100 (33%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81-oD3qvAOL._AC_UL320_.jpg",
    title: "Men's Solid Regular Fit T-Shirt",
    rating: "4.0 out of 5 stars",
    dis_price: "699",
    org_price: "?729",
    discount: "Save ?30 (4%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81lZRjb37rL._AC_UL320_.jpg",
    title: "U.S. Polo Assn. Men's Printed Cotton Vest",
    rating: "4.2 out of 5 stars",
    dis_price: "365",
    org_price: "?429",
    discount: "Save ?64 (15%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/81z6kRLSE4S._AC_UL320_.jpg",
    title: "Men's Trouser Premium Thermals (Inner Elastic)",
    rating: "4.2 out of 5 stars",
    dis_price: "458",
    org_price: "?580",
    discount: "Save ?122 (21%)",
    field7: "",
    category: "MenTopwear",
  },
  {
    path: "https://m.media-amazon.com/images/I/61LnC0OOHNL._AC_UL320_.jpg",
    title: "Printed Men Round Neck Full Sleeve T-Shirt",
    rating: "3.5 out of 5 stars",
    dis_price: "379",
    org_price: "?1,299",
    discount: "Save ?920 (71%)",
    field7: "",
    category: "MenTopwear",
  },

  {
    path: "https://m.media-amazon.com/images/I/71Y8rH2cJiL._AC_UY218_.jpg",
    title:
      "Samsung Galaxy M12 (White,6GB RAM, 128GB Storage) 6 Months Free Screen Replacement for Prime",
    rating: "4.1 out of 5 stars",
    dis_price: "13,499",
    org_price: "14,499",
    discount: "Save ₹1,000 (7%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/51RXNOBWAWS._AC_UY218_.jpg",
    title:
      "Vivo Y72 5G (Prism Magic, 8GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers",
    rating: "4.1 out of 5 stars",
    dis_price: "20,990",
    org_price: "24,990",
    discount: "Save ₹4,000 (16%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/71r69Y7BSeL._AC_UY218_.jpg",
    title:
      "Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate",
    rating: "4.1 out of 5 stars",
    dis_price: "11,499",
    org_price: "12,999",
    discount: "Save ₹1,500 (12%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/71KCwNV6MuL._AC_UY218_.jpg",
    title:
      "OPPO A31 (Mystery Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers",
    rating: "4.2 out of 5 stars",
    dis_price: "12,990",
    org_price: "15,990",
    discount: "Save ₹3,000 (19%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/817clKAKcqL._AC_UY218_.jpg",
    title:
      "Redmi 10 Prime (Phantom Black 4GB RAM 64GB | Helio G88 with extendable RAM Upto 2GB | FHD+ 90Hz Adaptive Sync Display)",
    rating: "4.0 out of 5 stars",
    dis_price: "12,499",
    org_price: "14,999",
    discount: "Save ₹2,500 (17%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/811lrGbXwIL._AC_UY218_.jpg",
    title:
      "Samsung Galaxy M21 2021 Edition (Arctic Blue, 4GB RAM, 64GB Storage) | FHD+ sAMOLED | 6 Months Free Screen Replacement for Prime (SM-M215GLBDINS)",
    rating: "4.2 out of 5 stars",
    dis_price: "12,999",
    org_price: "14,999",
    discount: "Save ₹2,000 (13%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/61CnyJ-IbML._AC_UY218_.jpg",
    title:
      "OPPO A31 (Fantasy White, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers",
    rating: "4.2 out of 5 stars",
    dis_price: "12,990",
    org_price: "15,990",
    discount: "Save ₹3,000 (19%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/715fp8nWEmL._AC_UY218_.jpg",
    title:
      "Redmi Note 10 Lite (Aurora Blue, 4GB RAM, 64GB Storage) | Alexa Built-in",
    rating: "4.2 out of 5 stars",
    dis_price: "12,999",
    org_price: "16,999",
    discount: "Save ₹4,000 (24%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/7162Y5fPdkL._AC_UY218_.jpg",
    title:
      "Samsung Galaxy M12 (Black,6GB RAM, 128GB Storage) 6 Months Free Screen Replacement for Prime",
    rating: "4.1 out of 5 stars",
    dis_price: "13,499",
    org_price: "15,499",
    discount: "Save ₹2,000 (13%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/71A9Vo1BatL._AC_UY218_.jpg",
    title:
      "Redmi 9 (Sporty Orange, 4GB RAM, 64GB Storage) | 2.3GHz Mediatek Helio G35 Octa core Processor",
    rating: "4.2 out of 5 stars",
    dis_price: "9,299",
    org_price: "10,999",
    discount: "Save ₹1,700 (15%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/61HxPIB0ZcL._AC_UY218_.jpg",
    title:
      "Vivo Y53s (Fantastic Rainbow, 8GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers",
    rating: "4.1 out of 5 stars",
    dis_price: "19,490",
    org_price: "22,990",
    discount: "Save ₹3,500 (15%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/61pDMzuZhKL._AC_UY218_.jpg",
    title:
      "Vivo Y33s (Mirror Black, 8GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers",
    rating: "4.3 out of 5 stars",
    dis_price: "18,990",
    org_price: "21,990",
    discount: "Save ₹3,000 (14%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/911TJ1CDbLL._AC_UY218_.jpg",
    title: "Redmi 9 Activ (Carbon Black, 6GB RAM, 128GB Storage)",
    rating: "4.2 out of 5 stars",
    dis_price: "10,999",
    org_price: "12,999",
    discount: "Save ₹2,000 (15%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/71Y8rH2cJiL._AC_UY218_.jpg",
    title:
      "Samsung Galaxy M12 (White,4GB RAM, 64GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate",
    rating: "4.1 out of 5 stars",
    dis_price: "11,499",
    org_price: "12,999",
    discount: "Save ₹1,500 (12%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/911TJ1CDbLL._AC_UY218_.jpg",
    title: "Redmi 9 Activ (Carbon Black, 4GB RAM, 64GB Storage)",
    rating: "4.2 out of 5 stars",
    dis_price: "9,299",
    org_price: "10,999",
    discount: "Save ₹1,700 (15%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/81aWyRY67SS._AC_UY218_.jpg",
    title:
      "Tecno Spark 7T(Jewel Blue, 4GB RAM, 64GB Storage) 6000 mAh Battery| 48 MP AI Dual Rear Camera",
    rating: "4.1 out of 5 stars",
    dis_price: "8,599",
    org_price: "10,999",
    discount: "Save ₹2,400 (22%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/61PGb+YfZWL._AC_UY218_.jpg",
    title:
      "realme narzo 50i (Mint Green, 2GB RAM+32GB Storage) - with No Cost EMI/Additional Exchange Offers",
    rating: "4.2 out of 5 stars",
    dis_price: "7,299",
    org_price: "7,999",
    discount: "Save ₹700 (9%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/71hgVYiuFXL._AC_UY218_.jpg",
    title:
      "realme narzo 50A (Oxygen Blue, 4GB RAM + 64GB Storage) - with No Cost EMI/Additional Exchange Offers",
    rating: "4.2 out of 5 stars",
    dis_price: "11,499",
    org_price: "12,999",
    discount: "Save ₹1,500 (12%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/71djAn3nxoL._AC_UY218_.jpg",
    title:
      "realme narzo 50i (Carbon Black, 4GB RAM+64GB Storage) - with No Cost EMI/Additional Exchange Offers",
    rating: "4.2 out of 5 stars",
    dis_price: "8,999",
    org_price: "9,999",
    discount: "Save ₹1,000 (10%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/81zgrTfdm7L._AC_UY218_.jpg",
    title:
      "Xifo Aimi Note 8 (4GB / 64 GB) with 6.26 Inch Touchscreen and 5000 mAh Smartphone (Fantasy Violet)",
    rating: "",
    dis_price: "6,999",
    org_price: "14,999",
    discount: "Save ₹8,000 (53%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/51hOmdg8STL._AC_UY218_.jpg",
    title:
      "Vivo Y20T (Purist Blue, 6GB RAM, 64GB Storage) No Cost EMI/Additional Exchange Offers (Y20T (6GB RAM, 64GB ROM))",
    rating: "3.8 out of 5 stars",
    dis_price: "15,489",
    org_price: "19,490",
    discount: "Save ₹4,001 (21%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/71VQXjN6R7S._AC_UY218_.jpg",
    title:
      "Mi 11X 5G Cosmic Black 6GB RAM 128GB ROM | SD 870 | DisplayMate A+ rated E4 AMOLED | Upto 18 Months No Cost EMI",
    rating: "4.0 out of 5 stars",
    dis_price: "27,999",
    org_price: "33,999",
    discount: "Save ₹6,000 (18%)",
    category: "Mobile",
  },
  {
    path: "https://m.media-amazon.com/images/I/81qR66aSGqL._AC_UL320_.jpg",
    title: "Analog Grey Dial Men's Watch-TW00ZR284E",
    rating: "4.3 out of 5 stars",
    dis_price: "1,555",
    org_price: "1,995",
    discount: "Save ₹440 (22%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71GUDIM1ylS._AC_UL320_.jpg",
    title: "Analog Brown Dial Men's Watch-TW023HG22",
    rating: "5.0 out of 5 stars",
    dis_price: "2,556",
    org_price: "3,195",
    discount: "Save ₹639 (20%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71kOC4qAaoL._AC_UL320_.jpg",
    title: "Analog Beige Dial Men's Watch-TWTG80SMU03",
    rating: "3.9 out of 5 stars",
    dis_price: "2,027",
    org_price: "3,695",
    discount: "Save ₹1,668 (45%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71eKO7XIQ0L._AC_UL320_.jpg",
    title: "Analog Black Dial Men's Watch-TWTG80SMU04",
    rating: "4.0 out of 5 stars",
    dis_price: "2,495",
    org_price: "4,195",
    discount: "Save ₹1,700 (41%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61IMRs+o0iL._AC_UL320_.jpg",
    title:
      "boAt Xtend Smartwatch with Alexa Built-in, 1.69� HD Display, Multiple Watch Faces, Stress Monitor, Heart & SpO2 Monitoring, 14 Sports Modes, Sleep Monitor & 5 ATM Water Resistance(Pitch Black)",
    rating: "4.2 out of 5 stars",
    dis_price: "2,999",
    org_price: "7,990",
    discount: "Save ₹4,991 (62%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71cT6st-7hL._AC_UL320_.jpg",
    title: "Analogue Men's Watch (Black Dial Black Colored Strap)",
    rating: "3.5 out of 5 stars",
    dis_price: "352",
    org_price: "2,499",
    discount: "Save ₹2,147 (86%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81BDpSIwu3L._AC_UL320_.jpg",
    title: "Analog Linear Designer Dial Men�s & Boy's Watch",
    rating: "3.6 out of 5 stars",
    dis_price: "299",
    org_price: "2,199",
    discount: "Save ₹1,900 (86%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81qcmjX9TrL._AC_UL320_.jpg",
    title: "Digital Men's Watch",
    rating: "3.8 out of 5 stars",
    dis_price: "699",
    org_price: "3,499",
    discount: "Save ₹2,800 (80%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81CwsCvUWqL._AC_UL320_.jpg",
    title: "Analog Two Hands Slim Watch for Men",
    rating: "3.8 out of 5 stars",
    dis_price: "359",
    org_price: "2,199",
    discount: "Save ₹1,840 (84%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81nj6IlZpVL._AC_UL320_.jpg",
    title: "Analog Day Date Functioning Stainless Steel Chain Watch for Men",
    rating: "3.8 out of 5 stars",
    dis_price: "339",
    org_price: "1,799",
    discount: "Save ₹1,460 (81%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/41EjE3W0jgL._AC_UL320_.jpg",
    title: "Analog Multi-Colour Dial Men's Watch - LR-COMBO-01-02-05",
    rating: "3.7 out of 5 stars",
    dis_price: "349",
    org_price: "2,499",
    discount: "Save ₹2,150 (86%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61xzuXWWozS._AC_UL320_.jpg",
    title:
      "Noise ColorFit Pro 2 Full Touch Control Smart Watch with 35g Weight & Upgraded LCD Display,IP68 Waterproof,Heart Rate Monitor,Sleep & Step Tracker,Call & Message Alerts & Long Battery Life (Jet Black)",
    rating: "4.0 out of 5 stars",
    dis_price: "2,799",
    org_price: "4,999",
    discount: "Save ₹2,200 (44%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71QoQPgheFL._AC_UL320_.jpg",
    title: "Stainless Steel Day and Date Blue Dial Analog Mens Watch Sam0507",
    rating: "3.6 out of 5 stars",
    dis_price: "246",
    org_price: "2,495",
    discount: "Save ₹2,249 (90%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61xBnF7kD5L._AC_UL320_.jpg",
    title:
      'boAt Flash Edition Smartwatch with Activity Tracker,Multiple Sports Modes,Full Touch 1.3" Screen,Sleep Monitor,Gesture, Camera & Music Control,IP68 Dust,Sweat & Splash Resistance(Lightning Black)',
    rating: "4.0 out of 5 stars",
    dis_price: "2,499",
    org_price: "6,990",
    discount: "Save ₹4,491 (64%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/51oldet9suL._AC_UL320_.jpg",
    title: "Analogue Men's Watch (Black Dial Black Colored Strap)",
    rating: "3.5 out of 5 stars",
    dis_price: "379",
    org_price: "1,999",
    discount: "Save ₹1,620 (81%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61epn29QG0L._AC_UL320_.jpg",
    title:
      'Noise ColorFit Pulse Spo2 Smart Watch with 10 days battery life, 60+ Watch Faces, 1.4" Full Touch HD Display Smartwatch, 24*7 Heart Rate Monitor Smart Band, Sleep Monitoring Smart Watches for Men and Women & IP68 Waterproof (Jet Black)',
    rating: "4.0 out of 5 stars",
    dis_price: "2,499",
    org_price: "4,999",
    discount: "Save ₹2,500 (50%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81ocfFVyYLL._AC_UL320_.jpg",
    title: "Combo of Black Watch, Wallet and Black Sunglasses for Men",
    rating: "3.8 out of 5 stars",
    dis_price: "499",
    org_price: "2,999",
    discount: "Save ₹2,500 (83%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61gscZYmaoL._AC_UL320_.jpg",
    title:
      "boAt Xtend Smartwatch with Alexa Built-in, 1.69� HD Display, Multiple Watch Faces, Stress Monitor, Heart & SpO2 Monitoring, 14 Sports Modes, Sleep Monitor & 5 ATM Water Resistance(Sandy Cream)",
    rating: "4.2 out of 5 stars",
    dis_price: "2,999",
    org_price: "7,990",
    discount: "Save ₹4,991 (62%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/510eVAZppWL._AC_UL320_.jpg",
    title: "Activity Tracker",
    rating: "3.1 out of 5 stars",
    dis_price: "499",
    org_price: "1,999",
    discount: "Save ₹1,500 (75%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81gVxyVYTmL._AC_UL320_.jpg",
    title: "Analog Black Dial Unisex Watch-NG38004PP06W / NG38004PP06W",
    rating: "4.2 out of 5 stars",
    dis_price: "636",
    org_price: "780",
    discount: "Save ₹144 (18%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/91aa8Ji8IOL._AC_UL320_.jpg",
    title:
      "Business Watch Mens Luxury Brand Casual Digital Man Watches Sports Military Brown SY-3022 Analog-Digital Black Dial Boys Watch - for Men (Brown)",
    rating: "3.9 out of 5 stars",
    dis_price: "1,049",
    org_price: "1,999",
    discount: "Save ₹950 (48%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/41h-yCo77hL._AC_UL320_.jpg",
    title:
      "Men Women Waterproof Luxury Fashion Military Quartz Sports Analog Wristwatch (Gold)",
    rating: "4.5 out of 5 stars",
    dis_price: "1,499",
    org_price: "1,999",
    discount: "Save ₹500 (25%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81CrndPTz1L._AC_UL320_.jpg",
    title: "Digital Men's Watch",
    rating: "3.8 out of 5 stars",
    dis_price: "699",
    org_price: "3,499",
    discount: "Save ₹2,800 (80%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/41fMGocKquL._AC_UL320_.jpg",
    title: "Analogue Men's/Boy's Watch (Black Dial & Strap)",
    rating: "3.4 out of 5 stars",
    dis_price: "399",
    org_price: "1,499",
    discount: "Save ₹1,100 (73%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71RDeXemoTL._AC_UL320_.jpg",
    title:
      "Analogue - Digital Men's Watch (Black Dial Black Colored Strap - 1155)",
    rating: "4.0 out of 5 stars",
    dis_price: "499",
    org_price: "1,499",
    discount: "Save ₹1,000 (67%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61lu1wutQ9L._AC_UL320_.jpg",
    title: "New Digital LED Men & Women's Combo of 2 Watches",
    rating: "3.2 out of 5 stars",
    dis_price: "287",
    org_price: "599",
    discount: "Save ₹312 (52%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81pLYGeE65L._AC_UL320_.jpg",
    title:
      "Stunning Look Crystals Studded in Dial with Day and Date Display Chain Watch for Men Boys",
    rating: "3.7 out of 5 stars",
    dis_price: "299",
    org_price: "1,599",
    discount: "Save ₹1,300 (81%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61inDpLrBES._AC_UL320_.jpg",
    title:
      "Brand - A Digital Watch with Square LED Shockproof Multi-Functional Automatic Black Color Strap Waterproof Digital Sports Watch for Men's Kids Watch for Boys Watch for Men Pack of 2",
    rating: "3.7 out of 5 stars",
    dis_price: "375",
    org_price: "2,499",
    discount: "Save ₹2,124 (85%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/51Gch-8pXkL._AC_UL320_.jpg",
    title:
      "MAGBOT QTX Bluetoth Wireless Smart Watch Fitness Band for Boys, Girls, Men, Women & Kids | Sports Watch for All Smart Phones I Heart Rate and BP Monitor",
    rating: "3.2 out of 5 stars",
    dis_price: "699",
    org_price: "2,999",
    discount: "Save ₹2,300 (77%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71SFb25cLkL._AC_UL320_.jpg",
    title: "Analogue Men's & Boy's Watch",
    rating: "3.5 out of 5 stars",
    dis_price: "237",
    org_price: "2,495",
    discount: "Save ₹2,258 (91%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/51ElW0h2OcL._AC_UL320_.jpg",
    title:
      "Metallic Blue Square LED Multi-Functional Automatic Sports Watch for Men's Kids Watch for Boys, Girls, Women- Watch for Men led Digital Digital Watch - for Men & Women (Black)",
    rating: "2.8 out of 5 stars",
    dis_price: "123",
    org_price: "199",
    discount: "Save ₹75.10 (38%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71oX+XG3h-S._AC_UL320_.jpg",
    title:
      "Brand - A Digital Watch with Square LED Shockproof Multi-Functional Automatic 5 Color Army Strap Waterproof Digital Sports Watch for Men's Kids Watch for Boys - Watch for Men",
    rating: "3.8 out of 5 stars",
    dis_price: "380",
    org_price: "1,999",
    discount: "Save ₹1,619 (81%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71gBmI1tP2L._AC_UL320_.jpg",
    title:
      "Analogue Brown Dial Leather Strap Watch with Wallet, Belt and Sunglass Set for Men & Boys",
    rating: "3.4 out of 5 stars",
    dis_price: "563",
    org_price: "799",
    discount: "Save ₹236 (30%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71t-RrgFsAL._AC_UL320_.jpg",
    title: "Outdoor Sports Digital Black Dial Mens Boys Watch (Black, Back)",
    rating: "4.1 out of 5 stars",
    dis_price: "499",
    org_price: "1,899",
    discount: "Save ₹1,400 (74%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81GAz1854PL._AC_UL320_.jpg",
    title: "Chronograph NOT Working Analog White Dial Men's Watch - ES 109",
    rating: "3.4 out of 5 stars",
    dis_price: "199",
    org_price: "1,495",
    discount: "Save ₹1,296 (87%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/51rSElPw1GL._AC_UL320_.jpg",
    title:
      "Fire-Boltt Ring Bluetooth Calling Smartwatch with SpO2 & 1.7� Metal Body with Blood Oxygen Monitoring, Continuous Heart Rate, Full Touch & Multiple Watch Faces (Black), M (BSW005)",
    rating: "4.1 out of 5 stars",
    dis_price: "4,980",
    org_price: "9,999",
    discount: "Save ₹5,019 (50%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/51eBKnjLnaL._AC_UL320_.jpg",
    title: "DIGITAL BLACK DIAL MEN�S WATCH",
    rating: "4.0 out of 5 stars",
    dis_price: "599",
    org_price: "999",
    discount: "Save ₹400 (40%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61g5FZOHQEL._AC_UL320_.jpg",
    title: "Enticer Men's Analog-Digital Dial Watch",
    rating: "4.4 out of 5 stars",
    dis_price: "2,395",
    org_price: "",
    discount: "Get it by",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/41D4ANL+piL._AC_UL320_.jpg",
    title:
      "Analogue Men's Watch (Pack of 3) (Multicolored Dial Multicolored Colored Strap)",
    rating: "3.6 out of 5 stars",
    dis_price: "355",
    org_price: "2,499",
    discount: "Save ₹2,144 (86%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/812moxVoL9L._AC_UL320_.jpg",
    title: "Analogue IPG Golden Dial Men�s & Boy's Watch",
    rating: "3.6 out of 5 stars",
    dis_price: "349",
    org_price: "2,999",
    discount: "Save ₹2,650 (88%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81+d6eSA0eL._AC_UL320_.jpg",
    title: "Analog Number Dial Leather Strap Watch for Men",
    rating: "3.8 out of 5 stars",
    dis_price: "227",
    org_price: "799",
    discount: "Save ₹572 (72%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/610d5dbMf1L._AC_UL320_.jpg",
    title:
      "Fire-Boltt Beast Pro Bluetooth Calling 1.69� with Voice Assistance, Local Music, Voice Recorder, Spo2 Monitoring, Heart Rate Full HD Touch Smartwatch with TWS Pairing - Black",
    rating: "3.9 out of 5 stars",
    dis_price: "4,999",
    org_price: "",
    discount: "Get it by",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71vKyimxsiL._AC_UL320_.jpg",
    title: "Analogue Men's Watch ( Black Dial & Strap )",
    rating: "3.4 out of 5 stars",
    dis_price: "379",
    org_price: "999",
    discount: "Save ₹620 (62%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61w9ISMyhiL._AC_UL320_.jpg",
    title: "Formal Analog Black Dial Men's Watch NM7924NM01/NN7924NM01",
    rating: "4.2 out of 5 stars",
    dis_price: "1,300",
    org_price: "1,675",
    discount: "Save ₹375 (22%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61aEzzAw7AL._AC_UL320_.jpg",
    title:
      "boAt Xtend Smartwatch with Alexa Built-in, 1.69� HD Display, Multiple Watch Faces, Stress Monitor, Heart & SpO2 Monitoring, 14 Sports Modes, Sleep Monitor & 5 ATM Water Resistance(Olive Green)",
    rating: "4.2 out of 5 stars",
    dis_price: "2,999",
    org_price: "7,990",
    discount: "Save ₹4,991 (62%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/41xnCnX36ML._AC_UL320_.jpg",
    title: "Sports Led Watches For Kids Digital Watch Boys Girls Women",
    rating: "3.6 out of 5 stars",
    dis_price: "279",
    org_price: "799",
    discount: "Save ₹520 (65%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/41IbFZ2MohL._AC_UL320_.jpg",
    title:
      "Digital Mens Watch Waterproof Sports Tactical Watch with LED Backlight Watch for Men (Black)",
    rating: "4.1 out of 5 stars",
    dis_price: "799",
    org_price: "1,999",
    discount: "Save ₹1,200 (60%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/81T-R+2CrCL._AC_UL320_.jpg",
    title: "Matrix Analogue Men's Watch (Black Dial Black Colored Strap)",
    rating: "3.4 out of 5 stars",
    dis_price: "299",
    org_price: "2,199",
    discount: "Save ₹1,900 (86%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61ie+Klw7zL._AC_UL320_.jpg",
    title:
      "Army Shockproof Waterproof Digital Sports Watch for Mens Kids Sports Watch for Boys - Military Army Watch for Men",
    rating: "3.9 out of 5 stars",
    dis_price: "280",
    org_price: "1,899",
    discount: "Save ₹1,619 (85%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/711MD93YAjL._AC_UL320_.jpg",
    title:
      "A Brand Army Shockproof Waterproof Digital Sports Watch for Mens Kids Sports Watch with Cap for Boys - Military Army Watch for Men",
    rating: "4.1 out of 5 stars",
    dis_price: "349",
    org_price: "999",
    discount: "Save ₹650 (65%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71Ykc0b6efL._AC_UL320_.jpg",
    title:
      "Sounce Compatible for Watch Band 42mm 44mm Adjustable Stainless Steel Mesh Wristband Sport Loop for Watch Series 6/5/4/3/2/1, SE",
    rating: "3.5 out of 5 stars",
    dis_price: "499",
    org_price: "1,899",
    discount: "Save ₹1,400 (74%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/51sabwgL+sL._AC_UL320_.jpg",
    title: "Digital Unisex-Child Watch (Black Dial) (Pack of 2)",
    rating: "3.4 out of 5 stars",
    dis_price: "265",
    org_price: "1,499",
    discount: "Save ₹1,234 (82%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61u2Rr7tBRL._AC_UL320_.jpg",
    title:
      "reflex 3.0 Unisex activity tracker - Full touch, color display, Heart rate monitor, Dual- tone silicone strap and up to 10 days battery life",
    rating: "3.8 out of 5 stars",
    dis_price: "1,995",
    org_price: "2,995",
    discount: "Save ₹1,000 (33%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61Q128QVBGL._AC_UL320_.jpg",
    title:
      "TAGG Verve NEO Smartwatch with 1.69'' Large Display, Real SPO2, and Real-Time Heart Rate Tracking, 10 Days Battery Backup, IPX68 Waterproof|| Black, Standard",
    rating: "4.0 out of 5 stars",
    dis_price: "1,799",
    org_price: "3,999",
    discount: "Save ₹2,200 (55%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71qEG7IZmzL._AC_UL320_.jpg",
    title: "Analogue Men's Watch ( Black Dial & Strap )",
    rating: "3.5 out of 5 stars",
    dis_price: "299",
    org_price: "999",
    discount: "Save ₹700 (70%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61fyBGuO18L._AC_UL320_.jpg",
    title:
      "Digital Sports Multi Functional Black Dial Watch for Mens Boys -315RED",
    rating: "3.8 out of 5 stars",
    dis_price: "299",
    org_price: "1,119",
    discount: "Save ₹820 (73%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/8117w76yVNL._AC_UL320_.jpg",
    title: "Chronograph Analogue and Digital Sports Watch for Men",
    rating: "3.8 out of 5 stars",
    dis_price: "712",
    org_price: "1,499",
    discount: "Save ₹787 (53%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71qdQGpsO9L._AC_UL320_.jpg",
    title:
      "Fashion Chronograph Black Orange Silicon Band Big Dial Watch for Men",
    rating: "",
    dis_price: "2,499",
    org_price: "4,999",
    discount: "Save ₹2,500 (50%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/61kPFKp64uL._AC_UL320_.jpg",
    title: "Analog Black Dial Men's Watch-TW033HG09",
    rating: "3.8 out of 5 stars",
    dis_price: "1,116",
    org_price: "1,395",
    discount: "Save ₹279 (20%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/71JExAGyjuL._AC_UL320_.jpg",
    title:
      "Watches Men Sport Quartz Watches Waterproof Wrist Watch Gift Three-Eye 6-pin Solid Leather Belt Watch",
    rating: "4.0 out of 5 stars",
    dis_price: "1,599",
    org_price: "2,500",
    discount: "Save ₹901 (36%)",
    category: "Watch",
  },
  {
    path: "https://m.media-amazon.com/images/I/51yC6vz9TYL._AC_UY218_.jpg",
    title:
      "PTron Studio Bluetooth Wireless Over Ear Headphones with Mic (Blue)",
    rating: "3.8 out of 5 stars",
    dis_price: "799",
    org_price: "1,999",
    discount: "Save ₹1,200 (60%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/61wEiyWwabL._AC_UY218_.jpg",
    title:
      "iClever BTH12 Kids Headphones, Colorful LED Lights Kids Bluetooth Headphones with 74/85/94dB Volume Limited Over Ear, 40H Playtime, Bluetooth 5.0, Built-in Mic for School/Tablet/PC/Airplane, Pink",
    rating: "4.5 out of 5 stars",
    dis_price: "2,294",
    org_price: "3,999",
    discount: "Save ₹1,705 (43%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/61xeIT6UHrL._AC_UY218_.jpg",
    title: "boAt Bassheads 900 Wired On Ear Headphones with Mic (Carbon Black)",
    rating: "4.2 out of 5 stars",
    dis_price: "699",
    org_price: "2,490",
    discount: "Save ₹1,791 (72%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/51xxA+6E+xL._AC_UY218_.jpg",
    title:
      "boAt Rockerz 450 Bluetooth Wireless On Ear Headphone with Mic (Luscious Black)",
    rating: "4.1 out of 5 stars",
    dis_price: "1,149",
    org_price: "3,990",
    discount: "Save ₹2,841 (71%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/61YvHa6o94L._AC_UY218_.jpg",
    title:
      "boAt Rockerz 510 Wireless Bluetooth On Ear Headphones with Mic (Raging Red)",
    rating: "4.2 out of 5 stars",
    dis_price: "1,399",
    org_price: "3,990",
    discount: "Save ₹2,591 (65%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/719elVA3FvL._AC_UY218_.jpg",
    title: "boAt Bassheads 100 in Ear Wired Earphones with Mic(Black)",
    rating: "4.1 out of 5 stars",
    dis_price: "329",
    org_price: "999",
    discount: "Save ₹670 (67%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/41BoLKMYjnL._AC_UY218_.jpg",
    title: "Sony MDR-ZX110A Wired On Ear Headphone without Mic (White)",
    rating: "4.0 out of 5 stars",
    dis_price: "690",
    org_price: "1,390",
    discount: "Save ₹700 (50%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/61gYxcIGjvL._AC_UY218_.jpg",
    title:
      "boAt Rockerz 550 Bluetooth Wireless Over Ear Headphone with Mic (Black)",
    rating: "4.1 out of 5 stars",
    dis_price: "1,499",
    org_price: "4,999",
    discount: "Save ₹3,500 (70%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/81lLGM7SKbL._AC_UY218_.jpg",
    title:
      "ZEBRONICS Zeb-Thunder Wireless Bluetooth Over The Ear Headphone with Mic (Blue)",
    rating: "3.8 out of 5 stars",
    dis_price: "699",
    org_price: "1,199",
    discount: "Save ₹500 (42%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/61ptzNC8r8L._AC_UY218_.jpg",
    title: "JBL C100SI by Harman Wired In Ear Headphones with Mic (Black)",
    rating: "4.1 out of 5 stars",
    dis_price: "679",
    org_price: "1,299",
    discount: "Save ₹620 (48%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/51P6DqgGnaS._AC_UY218_.jpg",
    title:
      "pTron Tangentbeat Bluetooth 5.0 Wireless Headphones with Deep Bass, Ergonomic Design, IPX4 Sweat/Waterproof Neckband, Magnetic Earbuds, Voice Assistant, Passive Noise Cancelation & Mic - (Dark Blue)",
    rating: "3.9 out of 5 stars",
    dis_price: "699",
    org_price: "2,499",
    discount: "Save ₹1,800 (72%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/51+5ZFoy6bS._AC_UY218_.jpg",
    title:
      "Masoori Extra Bass 2.0 On-Ear Headphones with Tangle Free Cable, 3.5mm Jack, Headset with Mic for Phone Calls.(Multicolour)",
    rating: "3.1 out of 5 stars",
    dis_price: "299",
    org_price: "1,299",
    discount: "Save ₹1,000 (77%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/71r6AArbBBL._AC_UY218_.jpg",
    title: "boAt Bassheads 900 Wired On Ear Headphones with Mic (Pearl White)",
    rating: "4.2 out of 5 stars",
    dis_price: "699",
    org_price: "2,490",
    discount: "Save ₹1,791 (72%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/61kWB+uzR2L._AC_UY218_.jpg",
    title:
      "boAt Rockerz 370 Bluetooth Wireless On Ear Headphone with Mic (Buoyant Black)",
    rating: "4.0 out of 5 stars",
    dis_price: "999",
    org_price: "2,499",
    discount: "Save ₹1,500 (60%)",
    category: "Headphone",
  },

  {
    path: "https://m.media-amazon.com/images/I/61l8G7a56QL._AC_UY218_.jpg",
    title: "Redgear Cloak Wired RGB Gaming Headphones with Microphone for PC",
    rating: "4.1 out of 5 stars",
    dis_price: "949",
    org_price: "1,799",
    discount: "Save ₹850 (47%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/81cJ1kUT1LL._AC_UY218_.jpg",
    title:
      "ZEBRONICS Zeb-Thunder Wireless Bluetooth Over The Ear Headphone with Mic (Red)",
    rating: "3.8 out of 5 stars",
    dis_price: "699",
    org_price: "1,199",
    discount: "Save ₹500 (42%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/513mDbXPxaS._AC_UY218_.jpg",
    title:
      "pTron Studio Over Ear Bluetooth 5.0 Wireless Headphones with Mic, Hi-Fi Sound with Deep Bass, 12Hrs Playback, Ergonomic & Lightweight Wireless Headset, Soft Cushions Earpads, Aux Port - (Black)",
    rating: "3.8 out of 5 stars",
    dis_price: "799",
    org_price: "1,999",
    discount: "Save ₹1,200 (60%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/61vvmibZy8L._AC_UY218_.jpg",
    title:
      "ZEBRONICS Zeb-Thunder Bluetooth Wireless On Ear Headphone with Mic (Sea Green)",
    rating: "3.8 out of 5 stars",
    dis_price: "699",
    org_price: "1,399",
    discount: "Save ₹700 (50%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/71L-jharorL._AC_UY218_.jpg",
    title:
      "Tribit BTH71 Bluetooth Wireless Over Ear Headphones with Mic (Multicolour)",
    rating: "4.2 out of 5 stars",
    dis_price: "2,209",
    org_price: "3,299",
    discount: "Save ₹1,090 (33%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/71q--MThR1L._AC_UY218_.jpg",
    title:
      "Boult Audio ProBass Thunder Over-Ear Wireless Bluetooth Headphones with Mic, Headset with Passive Noise Cancellation & Long Battery Life",
    rating: "3.8 out of 5 stars",
    dis_price: "899",
    org_price: "3,999",
    discount: "Save ₹3,100 (78%)",
    category: "Headphone",
  },
  {
    path: "https://m.media-amazon.com/images/I/71SMr4ZGf1L._AC_UY218_.jpg",
    title:
      "HP 15 Ryzen 3 Thin & Light 15.6-inch (39.6 cms) FHD Laptop (Ryzen 3 3250U/8GB/256GB SSD/Windows 10/MS Office/1.69 kg), 15s-gy0501AU, Silver",
    rating: "4.2 out of 5 stars",
    dis_price: "40,490",
    org_price: "46,055",
    discount: "Save 5,565 (12%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/61s7sJEpsVL._AC_UY218_.jpg",
    title:
      'Lenovo IdeaPad Slim 3 10th Gen Intel Core i3 14" (35.56cm) FHD Thin & Light Laptop (8GB/256GB SSD/Windows 11/MS Office 2021/2 Year Warranty/Platinum Grey/1.65Kg), 81WA00MGIN',
    rating: "4.0 out of 5 stars",
    dis_price: "39,490",
    org_price: "57,990",
    discount: "Save 18,500 (32%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/61DJffZzJNL._AC_UY218_.jpg",
    title:
      'Dell 15 (2021) Ryzen 3-3250U Laptop, 8GB DDR4, 256GB SSD, Win 10 + MS Office, Radeon Graphics, 15.6" (39.62 cms) FHD Display, Carbon Color (Inspiron 3515, D560523WIN9BE)',
    rating: "4.0 out of 5 stars",
    dis_price: "36,890",
    org_price: "52,437",
    discount: "Save 15,547 (30%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/71S8U9VzLTL._AC_UY218_.jpg",
    title:
      "ASUS VivoBook 15 (2020), 39.6 cm HD, Dual Core Intel Celeron N4020, Thin and Light Laptop (4GB RAM/256GB SSD/Integrated Graphics/Windows 10 Home/Transparent Silver/1.8 Kg), X515MA-BR002T",
    rating: "4.2 out of 5 stars",
    dis_price: "",
    org_price: "",
    discount: "",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._AC_UY218_.jpg",
    title:
      "Lenovo IdeaPad Slim 3 10th Gen Intel Core i3 15.6 inches FHD Business Laptop (8GB/256 GB SSD/UHD Graphics/Windows 10 Home/MS Office/Platinum Grey/1.7Kg), 81WB012DIN",
    rating: "4.2 out of 5 stars",
    dis_price: "41,490",
    org_price: "55,490",
    discount: "Save 14,000 (25%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/613WULNEr1L._AC_UY218_.jpg",
    title:
      "HP Chromebook 14-inch (35.56 cms) Thin & Light Touchscreen Laptop (Celeron N4020/4GB/64GB eMMC + 256GB Expandable Storage/Chrome OS/1.46 kgs Light/ Mineral Silver), 14a-na0003TU",
    rating: "3.7 out of 5 stars",
    dis_price: "26,990",
    org_price: "29,741",
    discount: "Save 2,751 (9%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/61+oXn1kh+L._AC_UY218_.jpg",
    title:
      "Acer Extensa 15 AMD 3020e Dual-core Processor 15.6' HD Display Thin and Light Laptop(4GB RAM/1 TB HDD/Win10/Integrated Graphics/Black/1.9 Kg), EX215-22",
    rating: "3.9 out of 5 stars",
    dis_price: "28,260",
    org_price: "35,990",
    discount: "Save 7,730 (21%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/51TACuT6SNL._AC_UY218_.jpg",
    title:
      'Dell 15 (2021) Athlon Silver 3050U Laptop, 4GB, 256GB SSD, Win 10 + MS Office, 15.6" (39.61 cms) FHD Display, Radeon Graphics, Soft Mint Color (Inspiron 3505, D560613WIN9SE)',
    rating: "4.2 out of 5 stars",
    dis_price: "32,010",
    org_price: "42,449",
    discount: "Save 10,439 (25%)",
    category: "Laptop",
  },

  {
    path: "https://m.media-amazon.com/images/I/61km1VkaCsL._AC_UY218_.jpg",
    title:
      'Lenovo IdeaPad Slim 1 Intel Celeron N4020 11.6" (29.46cm) HD Thin & Light Laptop (4GB/256 GB SSD/Windows 10/MS Office/Platinum Grey/1.2Kg), 81VT0071IN',
    rating: "3.9 out of 5 stars",
    dis_price: "27,462",
    org_price: "41,890",
    discount: "Save 14,428 (34%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/713he67k8HL._AC_UY218_.jpg",
    title:
      "Mi Notebook Horizon Edition 14 Intel Core i7-10510U 10th Gen Thin and Light Laptop(8GB/512GB SSD/Windows 10/Nvidia MX350 2GB Graphics/Grey/1.35Kg)(Without Webcam) XMA1904-AF",
    rating: "4.2 out of 5 stars",
    dis_price: "56,990",
    org_price: "65,999",
    discount: "Save 9,009 (14%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/51IsQHLroNL._AC_UY218_.jpg",
    title:
      'Dell Vostro 3405 14" (35.56cms) HD AG Display Laptop (AMD Silver 3050U / 4GB / 256 SSD / Integrated Graphics / Win 10 + MSO/ Black) D552147WIN9BE',
    rating: "3.6 out of 5 stars",
    dis_price: "29,990",
    org_price: "43,176",
    discount: "Save 13,186 (31%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/51AtifCisBL._AC_UY218_.jpg",
    title:
      'Lenovo V15 Intel Core i5 11th Gen 15.6" (39.62 cm) FHD Thin and Light Laptop (8GB RAM/256GB SSD/Windows 10/MS Office/Black/1.7 kg), 82KB00EYIN',
    rating: "3.9 out of 5 stars",
    dis_price: "48,990",
    org_price: "64,736",
    discount: "Save 15,746 (24%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/51j5Rb1tMUL._AC_UY218_.jpg",
    title:
      "HP 15s 11th Gen Intel Core i3 15.6 inches(39.6 cm) Laptop ( 8GB RAM/512GB SSD/ Windows 11/ MS Office/ Natural Silver/ 1.75kg) - 15s-du3564TU",
    rating: "4.1 out of 5 stars",
    dis_price: "44,903",
    org_price: "50,196",
    discount: "Save 5,293 (11%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/81hoonPUdxL._AC_UY218_.jpg",
    title:
      "HP Chromebook x360 14-inch (35.56 cms) Thin & Light Touchscreen Laptop (AMD 3015CE/4GB/64GB eMMC Storage/Chrome OS/Mineral Silver/1.49 kg), 14a-cb0007AU",
    rating: "4.0 out of 5 stars",
    dis_price: "29,990",
    org_price: "36,358",
    discount: "Save 6,368 (18%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/41BW06RWznL._AC_UY218_.jpg",
    title:
      "ASUS Chromebook Celeron Dual Core - (4 GB/32 GB EMMC Storage/Chrome OS) C223NA-GJ0074 Thin and Light Laptop (11.6 inch, Grey, 1 Kg)",
    rating: "5.0 out of 5 stars",
    dis_price: "18,999",
    org_price: "22,990",
    discount: "Save 3,991 (17%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/51YK6DgAAtL._AC_UY218_.jpg",
    title:
      'Lenovo Ideapad Slim 3 10th Gen Intel Core i3 15.6" (39.62cm) FHD Thin & Light Laptop (4GB/256 GB SSD/UHD Graphics/Windows 10/MS Office/2 Year Warranty/Platinum Grey/1.7Kg), 81WB0112IN + 15.6" Backpack',
    rating: "4.1 out of 5 stars",
    dis_price: "37,589",
    org_price: "53,709",
    discount: "Save 16,120 (30%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/51z0Sd72wTL._AC_UY218_.jpg",
    title:
      "AVITA Cosmos 2 in 1 Celeron Dual Core - (4 GB/64 GB EMMC Storage/Windows 10 Home) NS12T5IN021P 2 in 1 Laptop (11.6 inch, Charcoal Grey, 1.327 kg)",
    rating: "3.7 out of 5 stars",
    dis_price: "15,990",
    org_price: "23,490",
    discount: "Save 7,500 (32%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/61PEQTdVsmL._AC_UY218_.jpg",
    title:
      "(Renewed) Lenovo IdeaPad Gaming 3 Intel Core i5 10th Gen 15.6-inch (39.6 cm) FHD 120Hz IPS Gaming Laptop (8GB/512 SSD/Windows 10/NVIDIA GTX 1650 4GB GDDR6/Onyx Black/2.2Kg), 81Y401APIN",
    rating: "",
    dis_price: "51,849",
    org_price: "60,750",
    discount: "Save 8,901 (14%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/914o5xV1+8L._AC_UY218_.jpg",
    title:
      'ASUS TUF Gaming F15 Laptop 15.6" (39.62 cms) FHD 144Hz, Intel Core i5-10300H 10th Gen, GeForce GTX 1650 4GB GDDR6 Graphics (8GB RAM/512GB NVMe SSD/Windows 10/Fortress Gray/2.30 Kg), FX566LH-HN257T',
    rating: "4.4 out of 5 stars",
    dis_price: "61,990",
    org_price: "84,990",
    discount: "Save 23,000 (27%)",
    category: "Laptop",
  },
  {
    path: "https://m.media-amazon.com/images/I/61WNxdAeAoL._AC_UY218_.jpg",
    title:
      "Lenovo IdeaPad Slim 5 11th Gen Intel Core i5 15.6 inches FHD IPS Business Laptop (16GB/512GB SSD/Windows 10 Home/MS Office/Backlit Keyboard/Fingerprint Reader/Graphite Grey/1.66Kg), 82FG014DIN",
    rating: "4.2 out of 5 stars",
    dis_price: "62,990",
    org_price: "1,04,290",
    discount: "Save 41,300 (40%)",
    category: "Laptop",
  },
];

export function getItem() {
  const itemList = [...item];
  return itemList;
}
